### PR TITLE
Add instructions on how to install wordpress using bitpoke/stack

### PR DESCRIPTION
**Pull request by nachtmaar**
This PR brings in all the changes that are required to install Wordpress using bitbpoke/stack.

New changes:

- Use `bitpoke ingress` class instead of k3s traefik
- Generate `SSH config` as terraform output
- Add `dns hint` in terraform output
- use Hetzner `cx21` server (even though cx11 should work as well, but cx21 has a better performance per cost)
- Add note about how to `upgrade` Wordpress
- Add `troubleshooting` section
- create markdown `TOC`
- mention `kubectl tree` plugin

ToDo:
- [x] disable traefik in k3s by default
- [x] install letsencrypt issuers
- [x] remove installation of Wordpress and mysql CRs from readme (bitpoke/stack charts install them)

### CODE REVIEW

**Comment by nachtmaar** [comment]
Related: 
- https://github.com/bitpoke/stack/issues/131
- https://github.com/bitpoke/stack/pull/130
- https://github.com/bitpoke/wordpress-operator/pull/98

**Comment by uhlhosting** [comment]
@nachtmaar have you managed to get it working with Bitpoke? Including the dashboard?

**Comment by nachtmaar** [comment]
@uhlhosting I am coming closer :-D I realised there is the `bitpoke/stack` helm chart and that I don't need to install the Wordpress and mysql operator myself. And I was also able to deploy an instance of `bitpoke/wordpress-site` yesterday.
Pointing the IP at my cluster works as well, but there is a problem with lets encrypt. 

I will add the details later. How about you @uhlhosting ?

**Comment by uhlhosting** [comment]
@nachtmaar Just got it back for testing yet first will need to see if it can work on hetzner with Talos since thats what I am looking to use. I got a first deployment on minikube so the stack deployment was fixed, since was not working on last attempts. Will give it a go on proxmox/talos too, yet first will wait for a reply from the devs in relation to the dashboard, see if this can be ported too since they made it working for GCP only in past.

**Comment by nachtmaar** [comment]
@uhlhosting I did get my first successful installation using `letsencrypt`. There seems to be clash between `traefik` and `bitpoke-stack` ingress class because they both fight for the same port. I removed traefik for now. Need to find an automated way of doing it however. 

I am not aware of any dashboard can you send me a link ?

**Comment by nachtmaar** [comment]
@uhlhosting I have my Wordpress instance up and running and updated the documentation accordingly. Any feedback from your site on the documentation is more than welcome 😃

**Comment by uhlhosting** [comment]
@nachtmaar Will surely give it a try with our testing Talos deployment since we decided to give talos a chance as favourite minimal footprint and secure k8s deployment. Not to mention they have the most enjoyable and helpful community support around it!

**Pull request merged**
